module.exports = {
  MALFORMED_REQUEST: "無效的JSON請求",
  PLAYER_MISSED: "請求中缺少player參數",
  PLAYER_NOT_VALID: "參數player包含不支持的符號",
  AGENT_MISSED: "請求中缺少agent參數",
  HALL_MISSED: "請求中缺少hall參數",
  AGENT_DIFFERENT: "該玩家的帳戶已創建在跟agent參數不同的agent底下",
  IP_DISABLED: "此IP區域受限",
  PLAYER_FAIL: "玩家訊息發生錯誤",
  CREATE_PLAYER_FAIL: "建立玩家失敗",
  REPAIR_NOT_FOUND: "無效的uid",
  TOKEN_NOT_VALID: "無效的token",
  RATE_NOT_VALID: "無效的匯率",
  DUPLICATE_UID: "此uid已建立",
  INSUFFICIENT_FUNDS: "玩家的餘額不足",
  TRANSFER_NOT_VALID: "交易失效",
  GAME_FAIL: "遊戲訊息發生錯誤",
  TOKEN_FAIL: "玩家金鑰發生錯誤",
  AMOUNT_MISSED: "請求中缺少amount參數",
  AMOUNT_NOT_VALID: "參數amount不是整數或少於0",
  TYPE_MISSED: "請求中缺少type參數",
  TYPE_NOT_VALID: "請求type參數是無效的",
  UID_MISSED: "請求中缺少uid參數",
  UID_NOT_VALID: "參數uid包含不支持的符號",
  RECEIPT_NOT_FOUND: "無效的uid",
  INFO_NOT_FOUND: "查無此訊息",
}
